// Telegram kirish oynasi uchun davlatlar — `lib/widgets/tg_countries.dart` dan.
// [iso, nom, kod, shablon] — shablonda `X` bitta raqam, bo'sh joy ajratgich.

const RAW = [
  ['AF', "Afg'oniston", '93', 'XXX XXX XXX'],
  ['AL', 'Albaniya', '355', 'XX XXX XXXX'],
  ['AS', 'American Samoa', '1684', 'XXX XXXX'],
  ['AD', 'Andorra', '376', 'XX XX XX'],
  ['AO', 'Angola', '244', 'XXX XXX XXX'],
  ['AI', 'Anguilla', '1264', 'XXX XXXX'],
  ['FT', 'Anonymous Numbers', '888', 'XXXX XXXX'],
  ['AG', 'Antigua & Barbuda', '1268', 'XXX XXXX'],
  ['US', 'AQSH', '1', 'XXX XXX XXXX'],
  ['AR', 'Argentina', '54', ''],
  ['AM', 'Armaniston', '374', 'XX XXX XXX'],
  ['AW', 'Aruba', '297', 'XXX XXXX'],
  ['AU', 'Avstraliya', '61', 'XXX XXX XXX'],
  ['AT', 'Avstriya', '43', ''],
  ['AE', 'BAA', '971', 'XX XXX XXXX'],
  ['BS', 'Bahamas', '1242', 'XXX XXXX'],
  ['BH', 'Bahrayn', '973', 'XXXX XXXX'],
  ['BD', 'Bangladesh', '880', ''],
  ['BB', 'Barbados', '1246', 'XXX XXXX'],
  ['BY', 'Belarus', '375', 'XX XXX XXXX'],
  ['BE', 'Belgiya', '32', 'XXX XX XX XX'],
  ['BZ', 'Belize', '501', ''],
  ['BJ', 'Benin', '229', 'XX XXX XXX'],
  ['BM', 'Bermuda', '1441', 'XXX XXXX'],
  ['BT', 'Bhutan', '975', 'XX XXX XXX'],
  ['BG', 'Bolgariya', '359', ''],
  ['BO', 'Bolivia', '591', 'X XXX XXXX'],
  ['BQ', 'Bonaire, Sint Eustatius & Saba', '599', ''],
  ['BA', 'Bosnia & Herzegovina', '387', 'XX XXX XXX'],
  ['BW', 'Botswana', '267', 'XX XXX XXX'],
  ['BR', 'Braziliya', '55', 'XX XXXXX XXXX'],
  ['VG', 'British Virgin Islands', '1284', 'XXX XXXX'],
  ['BN', 'Brunei Darussalam', '673', 'XXX XXXX'],
  ['BF', 'Burkina Faso', '226', 'XX XX XX XX'],
  ['BI', 'Burundi', '257', 'XX XX XXXX'],
  ['GB', 'Buyuk Britaniya', '44', 'XXXX XXXXXX'],
  ['KH', 'Cambodia', '855', ''],
  ['CM', 'Cameroon', '237', 'XXXX XXXX'],
  ['CV', 'Cape Verde', '238', 'XXX XXXX'],
  ['KY', 'Cayman Islands', '1345', 'XXX XXXX'],
  ['CF', 'Central African Rep.', '236', 'XX XX XX XX'],
  ['TD', 'Chad', '235', 'XX XX XX XX'],
  ['CZ', 'Chexiya', '420', 'XXX XXX XXX'],
  ['CL', 'Chile', '56', 'X XXXX XXXX'],
  ['CO', 'Colombia', '57', 'XXX XXX XXXX'],
  ['KM', 'Comoros', '269', 'XXX XXXX'],
  ['CD', 'Congo (Dem. Rep.)', '243', 'XX XXX XXXX'],
  ['CG', 'Congo (Rep.)', '242', 'XX XXX XXXX'],
  ['CK', 'Cook Islands', '682', ''],
  ['CR', 'Costa Rica', '506', 'XXXX XXXX'],
  ['CW', 'Curaçao', '599', ''],
  ['CI', 'Côte d`Ivoire', '225', 'XX XXX XXX'],
  ['DK', 'Daniya', '45', 'XXXX XXXX'],
  ['IO', 'Diego Garcia', '246', 'XXX XXXX'],
  ['DJ', 'Djibouti', '253', 'XX XX XX XX'],
  ['DM', 'Dominica', '1767', 'XXX XXXX'],
  ['DO', 'Dominican Rep.', '1', 'XXX XXX XXXX'],
  ['EC', 'Ecuador', '593', 'XX XXX XXXX'],
  ['ET', 'Efiopiya', '251', 'XX XXX XXXX'],
  ['SV', 'El Salvador', '503', 'XXXX XXXX'],
  ['GQ', 'Equatorial Guinea', '240', 'XXX XXX XXX'],
  ['ER', 'Eritrea', '291', 'X XXX XXX'],
  ['IR', 'Eron', '98', 'XXX XXX XXXX'],
  ['EE', 'Estoniya', '372', ''],
  ['FK', 'Falkland Islands', '500', ''],
  ['FO', 'Faroe Islands', '298', 'XXX XXX'],
  ['FJ', 'Fiji', '679', ''],
  ['PH', 'Filippin', '63', 'XXX XXX XXXX'],
  ['FI', 'Finlandiya', '358', ''],
  ['FR', 'Fransiya', '33', 'X XX XX XX XX'],
  ['GF', 'French Guiana', '594', ''],
  ['PF', 'French Polynesia', '689', ''],
  ['GA', 'Gabon', '241', 'X XX XX XX'],
  ['GM', 'Gambia', '220', 'XXX XXXX'],
  ['DE', 'Germaniya', '49', ''],
  ['GH', 'Ghana', '233', ''],
  ['GI', 'Gibraltar', '350', 'XXXX XXXX'],
  ['HK', 'Gonkong', '852', 'X XXX XXXX'],
  ['GL', 'Greenland', '299', 'XXX XXX'],
  ['GD', 'Grenada', '1473', 'XXX XXXX'],
  ['GR', 'Gretsiya', '30', 'XXX XXX XXXX'],
  ['GE', 'Gruziya', '995', 'XXX XXX XXX'],
  ['GP', 'Guadeloupe', '590', 'XXX XX XX XX'],
  ['GU', 'Guam', '1671', 'XXX XXXX'],
  ['GT', 'Guatemala', '502', 'X XXX XXXX'],
  ['GN', 'Guinea', '224', 'XXX XXX XXX'],
  ['GW', 'Guinea-Bissau', '245', 'XXX XXXX'],
  ['GY', 'Guyana', '592', ''],
  ['HT', 'Haiti', '509', ''],
  ['IN', 'Hindiston', '91', 'XXXXX XXXXX'],
  ['HN', 'Honduras', '504', 'XXXX XXXX'],
  ['ID', 'Indoneziya', '62', ''],
  ['JO', 'Iordaniya', '962', 'X XXXX XXXX'],
  ['IE', 'Irlandiya', '353', 'XX XXX XXXX'],
  ['IQ', 'Iroq', '964', 'XXX XXX XXXX'],
  ['IS', 'Islandiya', '354', 'XXX XXXX'],
  ['ES', 'Ispaniya', '34', 'XXX XXX XXX'],
  ['IL', 'Isroil', '972', 'XX XXX XXXX'],
  ['IT', 'Italiya', '39', ''],
  ['JM', 'Jamaica', '1876', 'XXX XXXX'],
  ['ZA', 'Janubiy Afrika', '27', 'XX XXX XXXX'],
  ['KR', 'Janubiy Koreya', '82', ''],
  ['DZ', 'Jazoir', '213', 'XXX XX XX XX'],
  ['CA', 'Kanada', '1', 'XXX XXX XXXX'],
  ['KE', 'Keniya', '254', 'XXX XXX XXX'],
  ['CY', 'Kipr', '357', 'XXXX XXXX'],
  ['KI', 'Kiribati', '686', ''],
  ['XK', 'Kosovo', '383', 'XXXX XXXX'],
  ['CU', 'Kuba', '53', 'XXXX XXXX'],
  ['LA', 'Laos', '856', 'XX XX XXX XXX'],
  ['LV', 'Latviya', '371', 'XXX XXXXX'],
  ['LS', 'Lesotho', '266', 'XX XXX XXX'],
  ['LR', 'Liberia', '231', ''],
  ['LI', 'Liechtenstein', '423', ''],
  ['LT', 'Litva', '370', 'XXX XXXXX'],
  ['LB', 'Livan', '961', ''],
  ['LY', 'Liviya', '218', 'XX XXX XXXX'],
  ['LU', 'Luxembourg', '352', ''],
  ['MO', 'Macau', '853', 'XXXX XXXX'],
  ['MK', 'Macedonia', '389', 'XX XXX XXX'],
  ['MG', 'Madagascar', '261', 'XX XX XXX XX'],
  ['MY', 'Malayziya', '60', ''],
  ['MV', 'Maldives', '960', 'XXX XXXX'],
  ['ML', 'Mali', '223', 'XXXX XXXX'],
  ['MT', 'Malta', '356', 'XX XX XX XX'],
  ['MA', 'Marokash', '212', 'XX XXX XXXX'],
  ['MH', 'Marshall Islands', '692', ''],
  ['MQ', 'Martinique', '596', ''],
  ['MR', 'Mauritania', '222', 'XXXX XXXX'],
  ['MU', 'Mauritius', '230', ''],
  ['MX', 'Meksika', '52', ''],
  ['FM', 'Micronesia', '691', ''],
  ['EG', 'Misr', '20', 'XX XXXX XXXX'],
  ['MN', "Mo'g'uliston", '976', 'XX XX XXXX'],
  ['MD', 'Moldova', '373', 'XX XXX XXX'],
  ['MC', 'Monaco', '377', 'XXXX XXXX'],
  ['ME', 'Montenegro', '382', ''],
  ['MS', 'Montserrat', '1664', 'XXX XXXX'],
  ['MZ', 'Mozambique', '258', 'XX XXX XXXX'],
  ['MM', 'Myanma', '95', ''],
  ['NA', 'Namibia', '264', 'XX XXX XXXX'],
  ['NR', 'Nauru', '674', ''],
  ['NP', 'Nepal', '977', 'XX XXXX XXXX'],
  ['NC', 'New Caledonia', '687', ''],
  ['NI', 'Nicaragua', '505', 'XXXX XXXX'],
  ['NL', 'Niderlandiya', '31', 'X XX XX XX XX'],
  ['NE', 'Niger', '227', 'XX XX XX XX'],
  ['NG', 'Nigeriya', '234', ''],
  ['NU', 'Niue', '683', ''],
  ['NF', 'Norfolk Island', '672', ''],
  ['MP', 'Northern Mariana Islands', '1670', 'XXX XXXX'],
  ['NO', 'Norvegiya', '47', 'XXXX XXXX'],
  ['AZ', 'Ozarbayjon', '994', 'XX XXX XXXX'],
  ['UZ', "O'zbekiston", '998', 'XX XXX XX XX'],
  ['PW', 'Palau', '680', ''],
  ['PS', 'Palestine', '970', 'XXX XX XXXX'],
  ['PA', 'Panama', '507', 'XXXX XXXX'],
  ['PG', 'Papua New Guinea', '675', ''],
  ['PY', 'Paraguay', '595', 'XXX XXX XXX'],
  ['PE', 'Peru', '51', 'XXX XXX XXX'],
  ['PK', 'Pokiston', '92', 'XXX XXX XXXX'],
  ['PL', 'Polsha', '48', 'XXX XXX XXX'],
  ['PT', 'Portugaliya', '351', 'X XXXX XXXX'],
  ['PR', 'Puerto Rico', '1', 'XXX XXX XXXX'],
  ['QA', 'Qatar', '974', 'XX XXX XXX'],
  ['KG', "Qirg'iziston", '996', 'XXX XXXXXX'],
  ['KZ', "Qozog'iston", '7', 'XXX XXX XX XX'],
  ['KW', 'Quvayt', '965', 'XXXX XXXX'],
  ['RU', 'Rossiya', '7', 'XXX XXX XXXX'],
  ['RO', 'Ruminiya', '40', 'XXX XXX XXX'],
  ['RW', 'Rwanda', '250', 'XXX XXX XXX'],
  ['RE', 'Réunion', '262', 'XXX XXX XXX'],
  ['SH', 'Saint Helena', '290', 'XX XXX'],
  ['SH', 'Saint Helena', '247', 'XXXX'],
  ['KN', 'Saint Kitts & Nevis', '1869', 'XXX XXXX'],
  ['LC', 'Saint Lucia', '1758', 'XXX XXXX'],
  ['PM', 'Saint Pierre & Miquelon', '508', ''],
  ['VC', 'Saint Vincent & the Grenadines', '1784', 'XXX XXXX'],
  ['WS', 'Samoa', '685', ''],
  ['SM', 'San Marino', '378', 'XXX XXX XXXX'],
  ['SA', 'Saudiya Arabistoni', '966', 'XX XXX XXXX'],
  ['SN', 'Senegal', '221', 'XX XXX XXXX'],
  ['RS', 'Serbiya', '381', 'XX XXX XXXX'],
  ['SC', 'Seychelles', '248', 'X XX XX XX'],
  ['KP', 'Shimoliy Koreya', '850', ''],
  ['LK', 'Shri-Lanka', '94', 'XX XXX XXXX'],
  ['SE', 'Shvetsiya', '46', 'XX XXX XXXX'],
  ['CH', 'Shveytsariya', '41', 'XX XXX XXXX'],
  ['SL', 'Sierra Leone', '232', 'XX XXX XXX'],
  ['SG', 'Singapur', '65', 'XXXX XXXX'],
  ['SX', 'Sint Maarten', '1721', 'XXX XXXX'],
  ['SK', 'Slovakiya', '421', 'XXX XXX XXX'],
  ['SI', 'Sloveniya', '386', 'XX XXX XXX'],
  ['SB', 'Solomon Islands', '677', ''],
  ['SO', 'Somalia', '252', 'XX XXX XXX'],
  ['SS', 'South Sudan', '211', 'XX XXX XXXX'],
  ['SD', 'Sudan', '249', 'XX XXX XXXX'],
  ['SR', 'Suriname', '597', 'XXX XXXX'],
  ['SY', 'Suriya', '963', 'XXX XXX XXX'],
  ['SZ', 'Swaziland', '268', 'XXXX XXXX'],
  ['ST', 'São Tomé & Príncipe', '239', 'XX XXXXX'],
  ['TH', 'Tailand', '66', 'X XXXX XXXX'],
  ['TZ', 'Tanzania', '255', 'XX XXX XXXX'],
  ['TW', 'Tayvan', '886', 'XXX XXX XXX'],
  ['TL', 'Timor-Leste', '670', ''],
  ['TG', 'Togo', '228', 'XX XXX XXX'],
  ['TJ', 'Tojikiston', '992', 'XX XXX XXXX'],
  ['TK', 'Tokelau', '690', ''],
  ['TO', 'Tonga', '676', ''],
  ['TT', 'Trinidad & Tobago', '1868', 'XXX XXXX'],
  ['TN', 'Tunis', '216', 'XX XXX XXX'],
  ['TR', 'Turkiya', '90', 'XXX XXX XXXX'],
  ['TM', 'Turkmaniston', '993', 'XX XXXXXX'],
  ['TC', 'Turks & Caicos Islands', '1649', 'XXX XXXX'],
  ['TV', 'Tuvalu', '688', ''],
  ['UG', 'Uganda', '256', 'XX XXX XXXX'],
  ['UA', 'Ukraina', '380', 'XX XXX XX XX'],
  ['OM', 'Ummon', '968', 'XXXX XXXX'],
  ['UY', 'Uruguay', '598', 'X XXX XXXX'],
  ['VI', 'US Virgin Islands', '1340', 'XXX XXXX'],
  ['VU', 'Vanuatu', '678', ''],
  ['VE', 'Venezuela', '58', 'XXX XXX XXXX'],
  ['HU', 'Vengriya', '36', 'XXX XXX XXX'],
  ['VN', 'Vyetnam', '84', ''],
  ['WF', 'Wallis & Futuna', '681', ''],
  ['CN', 'Xitoy', '86', 'XXX XXXX XXXX'],
  ['HR', 'Xorvatiya', '385', ''],
  ['YL', 'Y-land', '42', ''],
  ['YE', 'Yaman', '967', 'XXX XXX XXX'],
  ['NZ', 'Yangi Zelandiya', '64', ''],
  ['JP', 'Yaponiya', '81', 'XX XXXX XXXX'],
  ['ZM', 'Zambia', '260', 'XX XXX XXXX'],
  ['ZW', 'Zimbabwe', '263', 'XX XXX XXXX'],
];

export const countries = RAW.map(([iso, name, code, pattern]) => ({
  iso, name, code, pattern,
  flag: String.fromCodePoint(...iso.toUpperCase().split('').map((c) => 0x1F1E6 + c.charCodeAt(0) - 65)),
  length: pattern.replace(/ /g, '').length,
  format(digits) {
    if (!pattern) return digits;
    let out = '';
    let i = 0;
    for (const ch of pattern) {
      if (i >= digits.length) break;
      if (ch === ' ') out += ' '; else out += digits[i++];
    }
    if (i < digits.length) out += digits.slice(i);
    return out;
  },
}));

export const countryByIso = (iso) => countries.find((c) => c.iso === `${iso}`.toUpperCase()) || null;

const MAIN_OF_CODE = { 1: 'US', 7: 'RU', 44: 'GB', 39: 'IT', 61: 'AU', 262: 'RE', 358: 'FI', 590: 'GP', 599: 'CW', 47: 'NO', 212: 'MA' };

/** Kod bo'yicha davlat; bir kodda bir nechta bo'lsa `prefer` saqlanadi. */
export function countryByCode(code, prefer = null) {
  if (!code) return null;
  if (prefer && prefer.code === code) return prefer;
  const main = MAIN_OF_CODE[code];
  const byMain = main ? countryByIso(main) : null;
  if (byMain) return byMain;
  return countries.find((c) => c.code === code) || null;
}

/** To'liq raqamdan (`998901234567`) davlat va qolgan qism. */
export function splitPhone(digits) {
  for (let n = 4; n >= 1; n--) {
    if (digits.length < n) continue;
    const c = countryByCode(digits.slice(0, n));
    if (c) return [c, digits.slice(n)];
  }
  return [null, digits];
}
